hugoblox:
  schema: "2.0"
  identity:
    name: Lizhang Chen
    type: person
    tagline: undergraduate | School of Electronics Engineering and Computer Science, Peking University
    description: Lizhang Chen is a junior Computer Science student at the School of EECS, Peking University. My current research interests lie in Multimodal Large Language Model
  theme:
    mode: system
    pack: marine
    colors:
      primary: ""
      secondary: ""
      neutral: ""
  typography:
    font: sans
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: Â© {year} {name}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
